### ISSUE TITLE
BUG: the .ipynb in the scripts directory throws two exceptions

### ISSUE THREAD

**Issue by johnh2o2** [NickC1/nonlinpy#1]
When running `skedm_examples.ipynb`, everything ran fine except for two `AttributeError`s, which were thrown because of misnamed functions:

* In 2D section: `X = data.chaos2D(sz=256)` throws `AttributeError` (`module skedm.data has no attribute chaos2D`) -- should be `chaos_2d` and not `chaos2D`
* Attribute error: `module 'skedm.data' has no attribute 'voronoiMatrix'` (should be `voronoi_matrix`).

**Comment by nickc1** [comment]
Thanks John. These are resolved in the following commit:

https://github.com/nickc1/skedm/commit/b063c5c81ab48bba179991cccc933f10ef8695bf
